[workspace]
members = ["core", "bindings"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["MatheMixX Developers"]
license = "MIT"
description = "MatheMixX statistical engine and desktop application"
